all: atascii2ascii ascii2atascii

.PHONY: clean

atascii2ascii: atascii2ascii.c
	cc -o atascii2ascii atascii2ascii.c

ascii2atascii: ascii2atascii.c
	cc -o ascii2atascii ascii2atascii.c

clean:
	rm ascii2atascii atascii2ascii
